# Generated by Django 2.2 on 2019-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogThermostat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='Температура')),
                ('co2', models.FloatField(blank=True, null=True, verbose_name='CO2')),
                ('hum', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('on', models.BooleanField(verbose_name='On')),
                ('current_state', models.CharField(max_length=20, verbose_name='Стан термостату')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
