# Generated by Django 2.2 on 2019-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order_execution',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок виконання'),
        ),
    ]
