# Generated by Django 2.2 on 2019-04-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logthermostat',
            name='hum',
        ),
    ]
