# Generated by Django 2.2 on 2019-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_phase_order_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='light_mode',
            field=models.BooleanField(default=False, verbose_name='RGB: True, UV: False'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='light_mode',
            field=models.BooleanField(default=False, verbose_name='RGB: True, UV: False'),
        ),
    ]
