# Generated by Django 2.2 on 2019-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_auto_20190421_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logthermostat',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
