# Generated by Django 2.2 on 2019-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0004_auto_20190604_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='set_co2',
            field=models.FloatField(default=0, verbose_name='Встановити рівень CO2'),
        ),
    ]
