# Generated by Django 2.2 on 2019-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0005_auto_20190604_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='set_co2',
            field=models.IntegerField(default=0, verbose_name='Встановити рівень CO2'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='set_temp',
            field=models.IntegerField(default=0, verbose_name='Встановити температуру'),
        ),
    ]
