# Generated by Django 2.2 on 2019-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0005_auto_20190424_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostat',
            name='for_program',
            field=models.BooleanField(default=False, verbose_name='Для використання програмою'),
        ),
    ]
