# Generated by Django 2.2 on 2019-04-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0006_thermostat_for_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldprogram',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ts.Thermostat'),
            preserve_default=False,
        ),
    ]
