# Generated by Django 2.2 on 2019-11-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0007_auto_20191105_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='looping',
            field=models.IntegerField(default=1, verbose_name='Кількість зациклень'),
        ),
    ]
