# Generated by Django 2.2.6 on 2019-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0008_program_looping'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активувати'),
        ),
    ]
